name: furniture_manager_flutter
description: Offline furniture manager with CSV/Excel import/export, sorting and bulk selection.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3
  path: ^1.9.0
  provider: ^6.1.2
  uuid: ^4.4.0
  file_picker: ^8.0.3
  path_provider: ^2.1.4
  csv: ^6.0.0
  excel: ^4.0.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
